remake app from MVC to MVP
Ievgen-Mykhailiuk/GoogleMapTask pull request #3
Opened 2022-08-25 07:46 UTC by Ievgen-Mykhailiuk

2022-08-26 09:03 UTC, Nikitax23 requested changes
Есть моменты к обсуждению. Хорошая работа, но нужно еще немного поменять поменять реализацию

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/SceneDelegate.swift
> +        let navigationController = UINavigationController()
Такой подход тоже существует, но он подразумевает под собой 1 роутер на весь проект. И 1 Assembly на весь проект.

Я предлагаю другой, более правильный:

У каждого модуля есть свой Assembly и свой Router.
Assembly собирает только этот модуль.
Роутер работает только с теми экранами, с которыми взаимодействует данный экран из модуля.
Router не принимает Assembly на входе.
И Assembly ничего не знает про роутер.
Роутер инитится только лишь в методе CreateModule .

В целом - концепт остаётся тот же, только меняется его реализация.

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Builder.swift
> +
здесь всё так, только это должно быть разделено на разные Builder . ну и Builder не принимает роутер

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/Presenter/ListViewPresenter.swift
> +    init(view: ListViewProtocol,
думаю, этого инита не должно быть в протоколе. 
Нам неважно, как будет выглядеть изнутри этот презентер. Нам важно, чтоб он реализовал протокол.

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/Presenter/ListViewPresenter.swift
> +    var model: [PlacesModel]
`var model: [PlacesModel]` => `var dataSource: [PlacesModel]` / `var list: [PlacesModel]`/ `var places: [PlacesModel]`

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/Presenter/ListViewPresenter.swift
> +    func showListOfPlaces()
`func showListOfPlaces()`
Мы не должны из вью говорить презентеру "покажи плейсы". 
Тут всё наоборот) 

viewController должен вызвать во `viewDidLoad` метод презентера . Некоторые называют его тоже `viewDidLoad` / `onViewDidLoad` / `setup` / `initialSetup`. 

И в этом методе (в твоём случае) ты уже вызовешь` self.view?.didUpdatePlaces(model: model)`

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/View/ListViewController.swift
> +    func didUpdatePlaces(model: [PlacesModel])
`func didUpdatePlaces(model: [PlacesModel])`

тут лучше просто `func update(with places: [PlacesModel])`

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/View/ListViewController.swift
> +    var places = [PlacesModel]() {
```
var places = [PlacesModel]() {
        didSet{
            tableView.dataSource = self
        }
    }
```

зачем так делать? 
delegate и dataSource всегда задаются на сетапе таблицы. и один раз. 
В твоем случае, каждый раз, когда задаются/меняются плейсы, каждый раз меняется датасорс

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/View/ListViewController.swift
> +        presenter.showListOfPlaces()
неправильно. 
1) почему `didShow`?)
2) этот метод вообще не нужен. 
3) на счет презентера и его названия метода я уже говорил в файле презентера

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/ListModule/View/ListViewController.swift
> +        self.places = model
а вот здесь нужно добавить релоад таблицы. 
Конечно, можно этот релоад поместить и в дид сет плейсов. 
Но можно контролировать это самому, и добавить это здесь.

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/MapModule/Presenter/MapViewPresenter.swift
> +    init(view: MapViewProtocol,
то же самое с инитом

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/MapModule/Presenter/MapViewPresenter.swift
> +    var model = [PlacesModel]()
почему модель не приватная? почему список у нас называется `model`?

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/MapModule/View/MapViewController.swift
> +    func didShowPlaces(model: [PlacesModel])
то же самое с didShowPlaces методом

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/MapModule/View/MapViewController.swift
> +        presenter.didTapOnShowListButton()
`presenter.didTapOnShowListButton()`
я бы сказал 
`presenter.showList()`

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/MapModule/View/MapViewController.swift
> +        commencedUpdatingLocation()
1) `commencedUpdatingLocation()` что за слово такое `commenced`?))) началось обновление локации? 
2) если ты используешь метод `startUpdatingLocation` только на старте, то viewController-у совсем не нужно о нём ничего знать. у тебя в таком случае будет общий метод , который ты будешь вызывать во `viewDidLoad`-e вьюхи, и внутри него уже вызовешь у презентера старт апдейта локации. 
И таким образом не нужно выносить `startUpdatingLocation` презентера тоже в протокол.

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Router.swift
> +
здесь реализация немного другая подразумевается.
Да, может быть базовый протокол роутера, которому соответствуют все под-протоколы (Роутер для каждого модуля свой, отдельный). Но я за то, чтоб роутер в инициализаторе принимал только UIViewController (мы всегда можем получить из него navigationController, если он есть. Но его ведь может и не быть).
а даже если он был бы, но опциональный, то достаточно обращаться к нему через ? , и не нужно разворачивать каждый раз

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
это делается немножко не так . 
 ты по сути не обработал статус пермиссий) 
 здесь нужно проверить статус, за тем если разрешено использовать локацию, то вернуть в КЛОУЖЕР - тру, если ещё не давали доступ - запросить доступ к локации, если запретили, то предложить юзеру перейти в настройки. (так как наше приложение без локации не имеет смысла). 
 
 то есть твой 
` manager.requestWhenInUseAuthorization()` нужно вшить сюда)

2022-08-26 09:03 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/MapModule/Presenter/MapViewPresenter.swift
> +        locationManager.delegate = self
я бы назвал метод `setupLocationManager()`, сделал его приватным, и вызывал в главном методе презентера (на этапе `viewDidLoad`)

2022-08-30 19:42 UTC, Nikitax23 requested changes
нужно немного больше вникать в то, что ты пишешь . и разбираться в коде , который ты написал или скопировал откуда-либо, понимать как он работает.

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +
всё хорошо, но где комплишн блоки?

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +    func showViewController(viewController: UIViewController,
```
func showViewController(viewController: UIViewController,
                            isModal: Bool,
                            animated: Bool)
```

=> 

```
func show(viewController: UIViewController,
                            isModal: Bool,
                            animated: Bool)
```

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +    func closeViewController(viewController: UIViewController,
```
func closeViewController(viewController: UIViewController,
                            animated: Bool)
```

=> 

```
func close(animated: Bool)
```

зачем тебе здесь передавать вью контроллер?

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +    func goBackToViewController(viewController: UIViewController,
```
func goBackToViewController(viewController: UIViewController,
                                animated: Bool)
```

=>
```

func goBack(to viewController: UIViewController,
                                animated: Bool)
```

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +        let presentingViewController = navigationController ?? viewController
`let presentingViewController = navigationController ?? viewController`

ты подумал, что ты написал? 
как твой viewController будет презентить сам себя? 

твой self.viewController может презентить твой viewController, который метод принимает в качестве параметра. но никак не сам себя)

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +        let presentingViewController = navigationController ?? viewController
то же самое с viewController здесь. только здесь его еще и не нужно передавать

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +        let presentingViewController = navigationController ?? viewController
только здесь это не presentingViewController, а presentedViewController. его запрезентили, а не он презентит

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: view)
можно вынести навигейшн контроллер внутрь `createMapModule`
и возвращать его в этом методе. 
он всё равно является наследником UIViewController, и все будет так же, только navigationController будет спрятан

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/List/ListAssembly.swift
> +protocol ListAssembling {
`ListAssembling`
почему Assembling?
пусть будет так же `ListAssembly`
только к классу реализации можно добавить префикс `Default`. так как это может быть дефолтной реализацией, и могут быть какие-то другие реализации данного протокола

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/List/ListRouter.swift
> +
в таких случаях надо или оставить // TODO: - , или добавить хоть какой-то метод close, хз. иначе объявление этого класса абсолютно бесполезно, так как даже нет протокола , который он реализует

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/List/Presenter/ListViewPresenter.swift
> +    private var places: [PlacesModel]
почему плейсы var ? они же нигде не меняются

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/List/Presenter/ListViewPresenter.swift
>      //MARK: - Show list method
`//MARK: - Show list method`
смысл такой марки?) если она называется, как метод (еще и старый)

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/Map/MapAssembly.swift
> +protocol MapAssembling {
то же самое с названием протокола и класса

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/Map/MapRouter.swift
> +protocol MapRouting {
`MapRouting`
откуда это окончание `ing`? 
то же самое с названием протокола и класса

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/Map/MapRouter.swift
> +                           isModal: self.viewController.isModal,
почему ты передаешь self.viewController.isModal здесь? ты понимаешь, что ты пишешь?
здесь параметр isModal, который ты передаёшь - это не то свойство, которое нужно получать откуда-то. это свойство, которое ты сам задаёшь. если оно true, то ты покажешь экран модально (запрезентишь), если false - добавишь в навигейшн стек (запушишь)

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/Map/View/MapViewController.swift
> +    func showPlaces(places: [PlacesModel])
`func showPlaces(places: [PlacesModel])`
когда у тебя в названии параметра есть то же самое слово, что и в названии метода, то принято делать так 

`func showPlaces(_ places: [PlacesModel])`

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/Map/View/MapViewController.swift
> +            errorDescription = error.description
прочитай свой код, пожалуйста. чем отличается внутренность одного и второго условия? нужны ли эти условия вообще??? 
и нужна ли тогда вообще переменная errorDescription?

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +import UIKit
вообще нехорошо здесь держать UIKit

да, это я сам так подсказал, и для этого проекта пусть будет здесь. Но в будущем от этого нужно будет уйти.

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +    private func createGoToSettingAlertAction() {
`createGoToSettingAlertAction`
подумай еще над названием метода

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +            .shared
зачем так делать с переносами? это перебор. 
это ж не SwiftUI

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +            if let url = URL(string:UIApplication.openSettingsURLString) {
```
if let url = URL(string:UIApplication.openSettingsURLString) {
                UIApplication.shared.open(url)
            }
```

открытие настроек можно вынести в экстеншн `UIApplication`

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +            .rootViewController?.showAlert(title: "Error",
когда у тебя нет понимания , какой сейчас вью контроллер отображается, нужно отображать самый верхний в иерархии. 
нужно показывать не с рандомного windows.first, а с того window , которое является keyWindow

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +                                           actions: [action])
нужно давать юзеру альтернативу: идти в настройки или не идти. Даже если приложение не имеет смысла без этого. Apple бы не пропустил такое в ревью в AppStore

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +        self.delegate?.didFailWithError(error: LocationError.noLocation)
а тут может быть только ошибка `LocationError.noLocation` ? 
или может есть смысл вернуть старую реализацию? 
почему ты так сделал ?

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +        ckeckAuthorizationStatus { status in
ты уверен что, здесь нужно проверять статус? 
или может при попытке сделать какое-то действие с локацией?

2022-08-30 19:42 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +    }
1) нет смысла создавать здесь свойства `allowed, notDetermined, notAllowed`. можно просто в комплишн передать соответствующее значение. 
2) `case .authorizedAlways, .authorizedWhenInUse:` здесь не хватает просто `.authorized`
3) `case .notDetermined:` внутри этого кейса следует вызвать запрос на локацию, а не выносить это на уровень выше

2022-08-31 11:31 UTC, Ievgen-Mykhailiuk commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +        ckeckAuthorizationStatus { status in
это делается немножко не так .
ты по сути не обработал статус пермиссий)
здесь нужно проверить статус, за тем если разрешено использовать локацию, то вернуть в КЛОУЖЕР - тру, если ещё не давали доступ - запросить доступ к локации, если запретили, то предложить юзеру перейти в настройки. (так как наше приложение без локации не имеет смысла).

то есть твой
manager.requestWhenInUseAuthorization() нужно вшить сюда)



Я запутался! Ты же сам написал что здесь надо проверить статус и вернуть в клоужер. 
В документации написано что этот метод вызывается при инициализации локейшн менеджера и при смене статуса! 
Ты имеешь ввиду при запросе локации проверять статус?

2022-08-31 11:32 UTC, Ievgen-Mykhailiuk commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +        ckeckAuthorizationStatus { status in
""""""""   это делается немножко не так .
ты по сути не обработал статус пермиссий)
здесь нужно проверить статус, за тем если разрешено использовать локацию, то вернуть в КЛОУЖЕР - тру, если ещё не давали доступ - запросить доступ к локации, если запретили, то предложить юзеру перейти в настройки. (так как наше приложение без локации не имеет смысла).
то есть твой
manager.requestWhenInUseAuthorization() нужно вшить сюда) """""""

Я запутался! Ты же сам написал что здесь надо проверить статус и вернуть в клоужер.
В документации написано что этот метод вызывается при инициализации локейшн менеджера и при смене статуса!
Ты имеешь ввиду при запросе локации проверять статус?

2022-08-31 11:37 UTC, Ievgen-Mykhailiuk commented on GoogleMapTask/GoogleMapTask/Services/LocationService.swift
> +    }
.authorized was deprecated in iOS 8.0
 Поэтому я его убрал

2022-09-01 12:32 UTC, Nikitax23 requested changes
пара минорных моментов и можно мержить!

2022-09-01 12:32 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +typealias EmptyBlock = () -> Void
этот тайпэлиас конечно может лежать в другом месте каком-то) с глобальными константами например

2022-09-01 12:32 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Application/BaseRouter.swift
> +            if let navigationController = navigationController {
```
if let navigationController = navigationController {
                navigationController.dismiss(animated: animated,
                                             completion: completion)
            } else {
            viewController.dismiss(animated: animated,
                                   completion: completion)
            }
```

это можно было бы вынести в  приватный метод `dismiss`

2022-09-01 12:32 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Extensions/UINavigationController+Extension.swift
> +    func pushViewController(_ viewController: UIViewController,
тут везде форматтирование поехало. проверь, пожалуйста, чтоб параметры были строго один под другим.

2022-09-01 12:32 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Modules/List/DefaultListRouter.swift
> +    func closeList()
`func closeList()` - необязательно здесь писать closeLIST. мы и так знаем, что мы на листе находимся) достаточно просто `close`

2022-09-01 13:22 UTC, Nikitax23 requested changes
последний момент и можно будет мержить)

2022-09-01 13:22 UTC, Nikitax23 commented on GoogleMapTask/GoogleMapTask/Extensions/UINavigationController+Extension.swift
> +        guard animated, let coordinator = transitionCoordinator else {
а смотри, тут у тебя трижды повторяется 
```
guard animated, let coordinator = transitionCoordinator else {
            DispatchQueue.main.async { completion?() }
            return
        }
        coordinator.animate(alongsideTransition: nil) { _ in completion?() }
```

можно это вынести в метод и переиспользовать

2022-09-01 14:07 UTC, Nikitax23 approved these changes
Молодец, можем мержить!

2022-09-06 11:19 UTC, merged